### ISSUE TITLE
Question 11 issue

### ISSUE THREAD

**Issue by XaspMe** [Yunique33/sql-academy-solutions#1]
Почему-то не срабатывает по limit 1, поправил на 2 и ок, условия тоже не устанавливают правильное количество, далее привожу правильный ответ.

SELECT name
FROM passenger
ORDER BY LENGTH(name) DESC
LIMIT 2;

**Comment by Yunique33** [comment]
Спасибо за комментарий, видимо на сайте изменили саму базу, добавили данные, и теперь людей с самым длинным именем стало 2.  С `limit 2` решение также не универсальное, так как если, условно, в базе вдруг таких имен станет 3, запрос опять поломается. Обновил решение на более универсальное.
